import {z} from 'zod';

/**
 * Owned represents a value generated by an LLM within a specific scope.
 *
 * Every value from an LLM carries metadata about its origin, confidence level,
 * and the scope that owns it. This enables tracking provenance and preventing
 * accidental context leaks between different security boundaries.
 *
 * @template T - The type of the wrapped value
 * @template S - The scope identifier (string literal type for compile-time safety)
 *
 * @example
 * ```typescript
 * // Admin scope generates sensitive data
 * const adminNotes: Owned<string, 'admin'> = {
 *   value: 'Internal review notes',
 *   confidence: 0.95,
 *   __scope: 'admin',
 *   traceId: 'trace-123'
 * };
 *
 * // Cannot accidentally use in customer context (compile-time error)
 * function sendToCustomer(data: Owned<string, 'customer'>) {
 *   // ... send to customer
 * }
 *
 * sendToCustomer(adminNotes); // ❌ Type error: 'admin' is not assignable to 'customer'
 * ```
 *
 * @see {@link createOwned} Factory function for creating Owned values
 * @see {@link isOwned} Type guard for runtime checking
 */
export interface Owned<T, S extends string> {
  /**
   * The actual value generated by the LLM.
   */
  readonly value: T;

  /**
   * Confidence score from 0 to 1 indicating the LLM's certainty about this value.
   *
   * - `1.0` = Highest confidence
   * - `0.0` = Lowest confidence
   *
   * @example
   * ```typescript
   * if (result.confidence < 0.8) {
   *   console.warn('Low confidence result, manual review recommended');
   * }
   * ```
   */
  readonly confidence: number;

  /**
   * The scope identifier that owns this value.
   *
   * This is a branded type that prevents mixing values from different scopes.
   * The `__scope` field is used for compile-time type checking to detect context leaks.
   *
   * @example
   * ```typescript
   * const adminData: Owned<User, 'admin'> = { ..., __scope: 'admin' };
   * const customerData: Owned<User, 'customer'> = { ..., __scope: 'customer' };
   *
   * // These are incompatible types at compile time
   * ```
   */
  readonly __scope: S;

  /**
   * Unique trace identifier for debugging and auditing.
   *
   * Links this value back to the specific LLM request that generated it.
   * Useful for debugging, logging, and tracking data provenance.
   *
   * @example
   * ```typescript
   * console.log(`Value generated by request ${owned.traceId}`);
   * ```
   */
  readonly traceId: string;
}

/**
 * Configuration options for creating an Owned value.
 *
 * @template T - The type of the value
 * @template S - The scope identifier
 */
export interface CreateOwnedOptions<T, S extends string> {
  /**
   * The value to wrap.
   */
  value: T;

  /**
   * The scope that owns this value.
   */
  scope: S;

  /**
   * Confidence score (0-1). Defaults to 1.0 if not provided.
   */
  confidence?: number;

  /**
   * Optional trace ID. Auto-generated if not provided.
   */
  traceId?: string;
}

/**
 * Creates an Owned value with the specified configuration.
 *
 * Factory function that wraps a value with ownership metadata.
 * Validates confidence is in range [0, 1] and generates trace IDs if needed.
 *
 * @template T - The type of the value
 * @template S - The scope identifier
 * @param options - Configuration for creating the Owned value
 * @returns An Owned value with all required metadata
 * @throws {Error} If confidence is not between 0 and 1
 *
 * @example
 * ```typescript
 * const userEmail = createOwned({
 *   value: 'user@example.com',
 *   scope: 'user-input',
 *   confidence: 0.99,
 * });
 *
 * console.log(userEmail.value); // 'user@example.com'
 * console.log(userEmail.__scope); // 'user-input'
 * console.log(userEmail.traceId); // Auto-generated UUID
 * ```
 *
 * @example
 * ```typescript
 * // With custom trace ID
 * const apiResponse = createOwned({
 *   value: { userId: 123, name: 'Alice' },
 *   scope: 'api-integration',
 *   confidence: 0.85,
 *   traceId: 'api-request-456'
 * });
 * ```
 */
export function createOwned<T, S extends string>(
  options: CreateOwnedOptions<T, S>,
): Owned<T, S> {
  const {value, scope, confidence = 1.0, traceId} = options;

  // Validate confidence range
  if (confidence < 0 || confidence > 1) {
    throw new Error(`Confidence must be between 0 and 1, got ${confidence}`);
  }

  return {
    value,
    confidence,
    __scope: scope,
    traceId: traceId ?? generateTraceId(),
  };
}

/**
 * Type guard to check if a value is an Owned type.
 *
 * Performs runtime validation to determine if an unknown value conforms
 * to the Owned interface structure.
 *
 * @param value - The value to check
 * @returns True if the value is an Owned type, false otherwise
 *
 * @example
 * ```typescript
 * function processData(data: unknown) {
 *   if (isOwned(data)) {
 *     // TypeScript knows data is Owned<unknown, string>
 *     console.log(`Confidence: ${data.confidence}`);
 *     console.log(`Scope: ${data.__scope}`);
 *     console.log(`Trace: ${data.traceId}`);
 *   }
 * }
 * ```
 *
 * @example
 * ```typescript
 * const maybeOwned = receiveFromAPI();
 *
 * if (isOwned(maybeOwned)) {
 *   // Safe to access Owned properties
 *   if (maybeOwned.confidence < 0.7) {
 *     console.warn('Low confidence value detected');
 *   }
 * }
 * ```
 */
export function isOwned(value: unknown): value is Owned<unknown, string> {
  return (
    typeof value === 'object' &&
    value !== null &&
    'value' in value &&
    'confidence' in value &&
    typeof (value as Record<string, unknown>).confidence === 'number' &&
    '__scope' in value &&
    typeof (value as Record<string, unknown>).__scope === 'string' &&
    'traceId' in value &&
    typeof (value as Record<string, unknown>).traceId === 'string'
  );
}

/**
 * Generates a unique trace identifier.
 *
 * Creates a trace ID using timestamp and random values for uniqueness.
 * Format: `trace-{timestamp}-{random}`
 *
 * @returns A unique trace identifier string
 * @internal
 */
function generateTraceId(): string {
  const timestamp = Date.now().toString(36);
  const random = Math.random().toString(36).substring(2, 9);
  return `trace-${timestamp}-${random}`;
}

/**
 * Zod schema for runtime validation of Owned values.
 *
 * Useful for validating data from external sources or untrusted inputs.
 *
 * @template T - The Zod schema for the value type
 * @template S - The Zod schema for the scope type (typically z.string())
 * @param valueSchema - Zod schema for the value field
 * @param scopeSchema - Zod schema for the scope field (optional, defaults to z.string())
 * @returns A Zod schema for the Owned type
 *
 * @example
 * ```typescript
 * import { z } from 'zod';
 *
 * const UserSchema = z.object({
 *   id: z.number(),
 *   name: z.string(),
 * });
 *
 * const OwnedUserSchema = ownedSchema(UserSchema, z.literal('admin'));
 *
 * // Validate untrusted data
 * const result = OwnedUserSchema.safeParse(untrustedData);
 * if (result.success) {
 *   const ownedUser: Owned<User, 'admin'> = result.data;
 * }
 * ```
 */
export function ownedSchema<
  T extends z.ZodTypeAny,
  S extends z.ZodTypeAny = z.ZodString,
>(
  valueSchema: T,
  scopeSchema?: S,
): z.ZodObject<{
  value: T;
  confidence: z.ZodNumber;
  __scope: S extends undefined ? z.ZodString : S;
  traceId: z.ZodString;
}> {
  return z.object({
    value: valueSchema,
    confidence: z.number().min(0).max(1),
    __scope: (scopeSchema ?? z.string()) as S extends undefined
      ? z.ZodString
      : S,
    traceId: z.string(),
  });
}
